#!/usr/bin/env python3
"""Interactive configuration wizard for devrig.toml and .env.

Called via: ./devrig config
Prompts for project settings and writes ready-to-use config files.
"""

import shutil
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
TEMPLATE_DIR = SCRIPT_DIR / "template"
CONFIG_FILE = PROJECT_DIR / "devrig.toml"
ENV_FILE = PROJECT_DIR / ".env"

MARKER = "# Added by devrig config"


def ask(prompt: str, default: str | None = None) -> str:
    """Prompt for input with an optional default."""
    suffix = f" [{default}]: " if default else ": "
    value = input(f"  {prompt}{suffix}").strip()
    return value if value else (default or "")


def ask_yn(prompt: str, default: bool = True) -> bool:
    """Prompt for yes/no."""
    hint = "Y/n" if default else "y/N"
    value = input(f"  {prompt} [{hint}]: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes")


def _git_config(key: str) -> str:
    """Read a git config value, returning empty string on failure."""
    try:
        result = subprocess.run(
            ["git", "config", "--global", key],
            capture_output=True, text=True, timeout=5,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception:
        return ""


def _setup_env() -> None:
    """Write devrig keys to .env, replacing any previous devrig block."""
    git_name = _git_config("user.name") or "Your Name"
    git_email = _git_config("user.email") or "you@example.com"
    git_name = ask("Git author name", git_name)
    git_email = ask("Git author email", git_email)

    new_block = [
        MARKER,
        "CLAUDE_PARAMS=--dangerously-skip-permissions",
        f"GIT_AUTHOR_NAME={git_name}",
        f"GIT_AUTHOR_EMAIL={git_email}",
    ]

    # Strip any existing devrig-managed block before writing
    if ENV_FILE.is_file():
        existing = ENV_FILE.read_text().splitlines()
        filtered = []
        skip = False
        for line in existing:
            if line.strip() == MARKER:
                skip = True
                continue
            if skip:
                # Skip non-empty lines that belong to the managed block
                if line.strip() and not line.startswith("#"):
                    continue
                skip = False
            filtered.append(line)
        # Remove trailing blank lines
        while filtered and not filtered[-1].strip():
            filtered.pop()
        if filtered:
            filtered.append("")  # blank separator
        filtered.extend(new_block)
        filtered.append("")
        ENV_FILE.write_text("\n".join(filtered))
        action = "Updated"
    else:
        ENV_FILE.write_text("\n".join(new_block) + "\n")
        action = "Written"

    print()
    print(f"  {action}: .env")


def main() -> None:
    if CONFIG_FILE.exists():
        if not ask_yn(f"{CONFIG_FILE.name} already exists. Overwrite?", default=False):
            print("  Aborted.")
            sys.exit(1)
        print()

    print()
    print("  devrig — Configuration")
    print("  ─────────────────────")
    print()

    project = ask("Project name", PROJECT_DIR.name)

    # Dev server
    print()
    has_dev_server = ask_yn("Start a dev server on the host?", default=True)
    dev_cmd = dev_port = dev_timeout = None
    if has_dev_server:
        dev_cmd = ask("Dev server command", "npm run dev")
        dev_port = ask("Dev server port (must match what the command listens on)", "3000")
        dev_timeout = ask("Readiness timeout (seconds)", "10")

    # Chrome bridge
    print()
    has_bridge = ask_yn("Enable Chrome browser bridge?", default=True)
    bridge_port = "9229"
    if has_bridge:
        bridge_port = ask("Bridge port", "9229")

    # Build the TOML
    lines = [
        f"# devrig — {project}",
        f"# Generated by: ./devrig config",
        f"",
        f'project = "{project}"',
    ]

    if has_dev_server:
        lines += [
            "",
            "[dev_server]",
            f'command = "{dev_cmd}"',
            f"port = {dev_port}",
        ]
        if dev_timeout != "10":
            lines.append(f"ready_timeout = {dev_timeout}")
    else:
        lines += [
            "",
            "# Dev server (uncomment and edit to enable):",
            "# [dev_server]",
            '# command = "npm run dev"',
            "# port = 3000",
        ]

    if has_bridge:
        lines += [
            "",
            "[chrome_bridge]",
            f"port = {bridge_port}",
        ]
    else:
        lines += [
            "",
            "# Chrome bridge (uncomment to enable):",
            "# [chrome_bridge]",
            "# port = 9229",
        ]

    lines.append("")
    CONFIG_FILE.write_text("\n".join(lines))
    print()
    print(f"  Written: {CONFIG_FILE.name}")

    # ── .env setup ───────────────────────────────────────────────────────
    print()
    _setup_env()

    # ── Starter files (if no existing project) ───────────────────────────
    if not (PROJECT_DIR / "package.json").exists() and TEMPLATE_DIR.is_dir():
        print()
        if ask_yn("No package.json found. Copy starter files (index.html + dev server)?"):
            for f in TEMPLATE_DIR.iterdir():
                shutil.copy2(f, PROJECT_DIR / f.name)
            print()
            print("  Copied: package.json, index.html")

    print()


if __name__ == "__main__":
    main()
