// @ts-check
import { createInterface } from 'node:readline/promises';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, basename } from 'node:path';

async function ask(rl, prompt, defaultVal) {
  const suffix = defaultVal ? ` [${defaultVal}]: ` : ': ';
  const answer = (await rl.question(`  ${prompt}${suffix}`)).trim();
  return answer || defaultVal || '';
}

async function askYN(rl, prompt, defaultVal = true) {
  const hint = defaultVal ? 'Y/n' : 'y/N';
  const answer = (await rl.question(`  ${prompt} [${hint}]: `)).trim().toLowerCase();
  if (!answer) return defaultVal;
  return answer === 'y' || answer === 'yes';
}

function parsePort(value, fallback) {
  const n = parseInt(value, 10);
  if (Number.isInteger(n) && n >= 1 && n <= 65535) return n;
  if (value && value !== String(fallback)) {
    console.warn(`[devrig] Invalid port '${value}' — using ${fallback}`);
  }
  return fallback;
}

function gitConfig(key) {
  try {
    return execFileSync('git', ['config', '--global', key], { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

/** Interactive configuration wizard. Generates devrig.toml and .env from user input. */
export async function configure(projectDir) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  let finished = false;
  rl.on('close', () => {
    if (!finished) {
      console.log('\nAborted.');
      process.exit(1);
    }
  });

  const tomlPath = join(projectDir, 'devrig.toml');
  if (existsSync(tomlPath)) {
    const overwrite = await askYN(rl, 'devrig.toml already exists. Overwrite?', false);
    if (!overwrite) {
      finished = true;
      rl.close();
      return;
    }
  }

  console.log('\n  devrig \u2014 Configuration');
  console.log(
    '  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n',
  );

  let project = await ask(rl, 'Project name', basename(projectDir));
  project = project
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/^-+|-+$/g, '');
  if (!project) project = 'my-project';

  // Environment selection
  console.log('\n  shared = Claude auth & memories in ~/.devrig/shared/ (reused across projects)');
  console.log("  local  = everything isolated in this project's .devrig/\n");
  const useShared = await askYN(rl, 'Use shared environment?');
  const environment = useShared ? 'shared' : 'local';

  // Devrig dashboard port
  const devrigPort = parsePort(await ask(rl, 'Devrig dashboard port', '8083'), 8083);

  // Git info
  console.log('\n  Git identity for commits Claude makes inside the container.\n');
  const gitName = await ask(rl, 'Git author name', gitConfig('user.name'));
  const gitEmail = await ask(rl, 'Git author email', gitConfig('user.email'));

  // ---------------------------------------------------------------------------
  // Build file contents and show preview before writing
  // ---------------------------------------------------------------------------

  // Build TOML
  let toml = `# devrig \u2014 ${project}\n# Generated by: devrig config\n\n`;
  toml += `project = "${project}"\n`;
  toml += `environment = "${environment}"\n\n`;
  toml += `[chrome_bridge]\nport = 9229\n\n`;
  toml += `[devrig]\nport = ${devrigPort}\n\n`;
  toml += `# [dev_server]\n# command = "npm run dev"\n# port = 3000\n\n`;
  toml += `# [claude]\n# version = "latest"\n`;

  // Build .env block
  const ENV_START = '# devrig:start';
  const ENV_END = '# devrig:end';
  const envBlock = [
    ENV_START,
    'CLAUDE_PARAMS=--dangerously-skip-permissions',
    `GIT_AUTHOR_NAME=${gitName}`,
    `GIT_AUTHOR_EMAIL=${gitEmail}`,
    ENV_END,
  ].join('\n');

  // Show file preview
  console.log('\n  Will write:\n');
  console.log('  \u2500\u2500 devrig.toml \u2500\u2500');
  console.log(toml.replace(/^/gm, '  '));
  console.log('  \u2500\u2500 .env \u2500\u2500');
  console.log(envBlock.replace(/^/gm, '  '));
  console.log('');

  const proceed = await askYN(rl, 'Write these files?');
  if (!proceed) {
    console.log('  Aborted.');
    finished = true;
    rl.close();
    return;
  }

  // ---------------------------------------------------------------------------
  // Write files
  // ---------------------------------------------------------------------------

  writeFileSync(tomlPath, toml);
  console.log(`\n  Wrote ${tomlPath}`);

  const envPath = join(projectDir, '.env');
  if (existsSync(envPath)) {
    let content = readFileSync(envPath, 'utf8');
    // Remove old sentinel-based block
    const startIdx = content.indexOf(ENV_START);
    const endIdx = content.indexOf(ENV_END);
    if (startIdx !== -1 && endIdx !== -1) {
      content = (content.slice(0, startIdx) + content.slice(endIdx + ENV_END.length)).trim();
    }
    // Also strip legacy marker blocks (pre-sentinel format)
    content = content.replace(/# Added by devrig config\n(?:[A-Z_]+=.*\n)*/g, '').trim();
    writeFileSync(envPath, (content ? content + '\n\n' : '') + envBlock + '\n');
  } else {
    writeFileSync(envPath, envBlock + '\n');
  }
  console.log(`  Wrote ${envPath}`);

  finished = true;
  rl.close();
}
