// @ts-check
import { createInterface } from 'node:readline/promises';
import { readFileSync, writeFileSync, existsSync, copyFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

async function ask(rl, prompt, defaultVal) {
  const suffix = defaultVal ? ` [${defaultVal}]: ` : ': ';
  const answer = (await rl.question(`  ${prompt}${suffix}`)).trim();
  return answer || defaultVal || '';
}

async function askYN(rl, prompt, defaultVal = true) {
  const hint = defaultVal ? 'Y/n' : 'y/N';
  const answer = (await rl.question(`  ${prompt} [${hint}]: `)).trim().toLowerCase();
  if (!answer) return defaultVal;
  return answer === 'y' || answer === 'yes';
}

function parsePort(value, fallback) {
  const n = parseInt(value, 10);
  return Number.isInteger(n) && n >= 1 && n <= 65535 ? n : fallback;
}

function gitConfig(key) {
  try {
    return execFileSync('git', ['config', '--global', key], { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

/** Interactive configuration wizard. Generates devrig.toml and .env from user input. */
export async function configure(projectDir) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  let finished = false;
  rl.on('close', () => {
    if (!finished) {
      console.log('\nAborted.');
      process.exit(1);
    }
  });

  const tomlPath = join(projectDir, 'devrig.toml');
  if (existsSync(tomlPath)) {
    const overwrite = await askYN(rl, 'devrig.toml already exists. Overwrite?', false);
    if (!overwrite) {
      finished = true;
      rl.close();
      return;
    }
  }

  console.log('\n  devrig \u2014 Configuration');
  console.log(
    '  \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n',
  );

  let project = await ask(rl, 'Project name', basename(projectDir));
  project = project
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/^-+|-+$/g, '');
  if (!project) project = 'my-project';
  const tool = await ask(rl, 'AI tool', 'claude');

  // Dev server
  const useDevServer = await askYN(rl, 'Start a dev server on the host?');
  let devCommand = '',
    devPort = 0,
    devTimeout = 0;
  if (useDevServer) {
    devCommand = await ask(rl, 'Dev server command', 'npm run dev');
    devPort = parsePort(await ask(rl, 'Dev server port', '3000'), 3000);
    devTimeout = parseInt(await ask(rl, 'Startup timeout (s)', '10'), 10) || 10;
  }

  // Chrome bridge
  const useChrome = await askYN(rl, 'Enable Chrome browser bridge?');
  let chromePort = 0;
  if (useChrome) {
    chromePort = parsePort(await ask(rl, 'Chrome debug port', '9229'), 9229);
  }

  // Build TOML
  let toml = `# devrig \u2014 ${project}\n# Generated by: devrig config\n\n`;
  toml += `tool = "${tool}"\nproject = "${project}"\n\n`;

  if (useDevServer) {
    toml += `[dev_server]\ncommand = "${devCommand}"\nport = ${devPort}\n`;
    if (devTimeout !== 10) toml += `ready_timeout = ${devTimeout}\n`;
    toml += '\n';
  } else {
    toml += `# [dev_server]\n# command = "npm run dev"\n# port = 3000\n\n`;
  }

  if (useChrome) {
    toml += `[chrome_bridge]\nport = ${chromePort}\n`;
  } else {
    toml += `# [chrome_bridge]\n# port = 9229\n`;
  }

  writeFileSync(tomlPath, toml);
  console.log(`\n  Wrote ${tomlPath}`);

  // .env setup
  const gitName = await ask(rl, 'Git author name', gitConfig('user.name'));
  const gitEmail = await ask(rl, 'Git author email', gitConfig('user.email'));

  const marker = '# Added by devrig config';
  const block = [
    marker,
    'CLAUDE_PARAMS=--dangerously-skip-permissions',
    `GIT_AUTHOR_NAME=${gitName}`,
    `GIT_AUTHOR_EMAIL=${gitEmail}`,
  ].join('\n');

  const envPath = join(projectDir, '.env');
  if (existsSync(envPath)) {
    let content = readFileSync(envPath, 'utf8');
    const re = new RegExp(`${marker}[\\s\\S]*?${marker}\\n?`, 'g');
    content = content.replace(re, '').trimEnd();
    writeFileSync(envPath, content + '\n\n' + block + '\n');
  } else {
    writeFileSync(envPath, block + '\n');
  }
  console.log(`  Wrote ${envPath}`);

  // Starter files
  if (!existsSync(join(projectDir, 'package.json'))) {
    const copyFiles = await askYN(rl, 'No package.json found. Copy starter template files?');
    if (copyFiles) {
      const tplDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'scaffold', 'template');
      for (const f of ['index.html', 'package.json', 'server.js']) {
        const src = join(tplDir, f);
        if (existsSync(src)) {
          copyFileSync(src, join(projectDir, f));
          console.log(`  Copied ${f}`);
        }
      }
    }
  }

  finished = true;
  rl.close();
}
